package exchange.antx.common.util;

import com.google.common.base.Throwables;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.MessageOrBuilder;
import com.google.protobuf.TypeRegistry;
import com.google.protobuf.util.JsonFormat;

import java.util.List;
import java.util.stream.Collectors;

public class PbUtil {

    private PbUtil() {
    }

    private static final TypeRegistry TYPE_REGISTRY = TypeRegistry.newBuilder()
            .add(amino.Amino.getDescriptor().getMessageTypes())
            .add(com.google.api.AnnotationsProto.getDescriptor().getMessageTypes())
            .add(com.google.api.AuthProto.getDescriptor().getMessageTypes())
            .add(com.google.api.BackendProto.getDescriptor().getMessageTypes())
            .add(com.google.api.BillingProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ClientProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ConfigChangeProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ConsumerProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ContextProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ControlProto.getDescriptor().getMessageTypes())
            .add(com.google.api.DistributionProto.getDescriptor().getMessageTypes())
            .add(com.google.api.DocumentationProto.getDescriptor().getMessageTypes())
            .add(com.google.api.EndpointProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ErrorReasonProto.getDescriptor().getMessageTypes())
            .add(com.google.api.FieldBehaviorProto.getDescriptor().getMessageTypes())
            .add(com.google.api.FieldInfoProto.getDescriptor().getMessageTypes())
            .add(com.google.api.HttpBodyProto.getDescriptor().getMessageTypes())
            .add(com.google.api.HttpProto.getDescriptor().getMessageTypes())
            .add(com.google.api.LabelProto.getDescriptor().getMessageTypes())
            .add(com.google.api.LaunchStageProto.getDescriptor().getMessageTypes())
            .add(com.google.api.LogProto.getDescriptor().getMessageTypes())
            .add(com.google.api.LoggingProto.getDescriptor().getMessageTypes())
            .add(com.google.api.MetricProto.getDescriptor().getMessageTypes())
            .add(com.google.api.MonitoredResourceProto.getDescriptor().getMessageTypes())
            .add(com.google.api.MonitoringProto.getDescriptor().getMessageTypes())
            .add(com.google.api.PolicyProto.getDescriptor().getMessageTypes())
            .add(com.google.api.QuotaProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ResourceProto.getDescriptor().getMessageTypes())
            .add(com.google.api.RoutingProto.getDescriptor().getMessageTypes())
            .add(com.google.api.ServiceProto.getDescriptor().getMessageTypes())
            .add(com.google.api.SourceInfoProto.getDescriptor().getMessageTypes())
            .add(com.google.api.SystemParameterProto.getDescriptor().getMessageTypes())
            .add(com.google.api.UsageProto.getDescriptor().getMessageTypes())
            .add(com.google.api.VisibilityProto.getDescriptor().getMessageTypes())
            .add(com.google.apps.card.v1.CardProto.getDescriptor().getMessageTypes())
            .add(com.google.cloud.ExtendedOperationsProto.getDescriptor().getMessageTypes())
            .add(com.google.cloud.audit.AuditLogProto.getDescriptor().getMessageTypes())
            .add(com.google.cloud.location.LocationsProto.getDescriptor().getMessageTypes())
            .add(com.google.geo.type.ViewportProto.getDescriptor().getMessageTypes())
            .add(com.google.logging.type.HttpRequestProto.getDescriptor().getMessageTypes())
            .add(com.google.logging.type.LogSeverityProto.getDescriptor().getMessageTypes())
            .add(com.google.longrunning.OperationsProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.AnyProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.ApiProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.DescriptorProtos.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.DurationProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.EmptyProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.FieldMaskProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.GoGoProtos.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.SourceContextProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.StructProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.TimestampProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.TypeProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.WrappersProto.getDescriptor().getMessageTypes())
            .add(com.google.protobuf.compiler.PluginProtos.getDescriptor().getMessageTypes())
            .add(com.google.rpc.CodeProto.getDescriptor().getMessageTypes())
            .add(com.google.rpc.ErrorDetailsProto.getDescriptor().getMessageTypes())
            .add(com.google.rpc.StatusProto.getDescriptor().getMessageTypes())
            .add(com.google.rpc.context.AttributeContextProto.getDescriptor().getMessageTypes())
            .add(com.google.rpc.context.AuditContextProto.getDescriptor().getMessageTypes())
            .add(com.google.shopping.type.TypesProto.getDescriptor().getMessageTypes())
            .add(com.google.type.CalendarPeriodProto.getDescriptor().getMessageTypes())
            .add(com.google.type.ColorProto.getDescriptor().getMessageTypes())
            .add(com.google.type.DateProto.getDescriptor().getMessageTypes())
            .add(com.google.type.DateTimeProto.getDescriptor().getMessageTypes())
            .add(com.google.type.DayOfWeekProto.getDescriptor().getMessageTypes())
            .add(com.google.type.DecimalProto.getDescriptor().getMessageTypes())
            .add(com.google.type.ExprProto.getDescriptor().getMessageTypes())
            .add(com.google.type.FractionProto.getDescriptor().getMessageTypes())
            .add(com.google.type.IntervalProto.getDescriptor().getMessageTypes())
            .add(com.google.type.LatLngProto.getDescriptor().getMessageTypes())
            .add(com.google.type.LocalizedTextProto.getDescriptor().getMessageTypes())
            .add(com.google.type.MoneyProto.getDescriptor().getMessageTypes())
            .add(com.google.type.MonthProto.getDescriptor().getMessageTypes())
            .add(com.google.type.PhoneNumberProto.getDescriptor().getMessageTypes())
            .add(com.google.type.PostalAddressProto.getDescriptor().getMessageTypes())
            .add(com.google.type.QuaternionProto.getDescriptor().getMessageTypes())
            .add(com.google.type.TimeOfDayProto.getDescriptor().getMessageTypes())
            .add(cometbft.abci.v2.Service.getDescriptor().getMessageTypes())
            .add(cometbft.abci.v2.Types.getDescriptor().getMessageTypes())
            .add(cometbft.crypto.v1.Keys.getDescriptor().getMessageTypes())
            .add(cometbft.crypto.v1.ProofOuterClass.getDescriptor().getMessageTypes())
            .add(cometbft.libs.bits.v1.Types.getDescriptor().getMessageTypes())
            .add(cometbft.p2p.v1.Conn.getDescriptor().getMessageTypes())
            .add(cometbft.p2p.v1.Pex.getDescriptor().getMessageTypes())
            .add(cometbft.p2p.v1.Types.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.BlockOuterClass.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.Canonical.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.Events.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.EvidenceOuterClass.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.Params.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.Types.getDescriptor().getMessageTypes())
            .add(cometbft.types.v2.ValidatorOuterClass.getDescriptor().getMessageTypes())
            .add(cometbft.version.v1.Types.getDescriptor().getMessageTypes())
            .add(cosmos.app.runtime.v1alpha1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.app.v1alpha1.ConfigOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.app.v1alpha1.Module.getDescriptor().getMessageTypes())
            .add(cosmos.app.v1alpha1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.auth.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.auth.v1beta1.Auth.getDescriptor().getMessageTypes())
            .add(cosmos.auth.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.auth.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.auth.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.authz.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.authz.v1beta1.Authz.getDescriptor().getMessageTypes())
            .add(cosmos.authz.v1beta1.Event.getDescriptor().getMessageTypes())
            .add(cosmos.authz.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.authz.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.authz.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.autocli.v1.Options.getDescriptor().getMessageTypes())
            .add(cosmos.autocli.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.bank.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.bank.v1beta1.Authz.getDescriptor().getMessageTypes())
            .add(cosmos.bank.v1beta1.Bank.getDescriptor().getMessageTypes())
            .add(cosmos.bank.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.bank.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.bank.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.base.abci.v1beta1.Abci.getDescriptor().getMessageTypes())
            .add(cosmos.base.node.v1beta1.Query.getDescriptor().getMessageTypes())
            .add(cosmos.base.query.v1beta1.Pagination.getDescriptor().getMessageTypes())
            .add(cosmos.base.reflection.v1beta1.Reflection.getDescriptor().getMessageTypes())
            .add(cosmos.base.reflection.v2alpha1.Reflection.getDescriptor().getMessageTypes())
            .add(cosmos.base.tendermint.v1beta1.Query.getDescriptor().getMessageTypes())
            .add(cosmos.base.tendermint.v1beta1.Types.getDescriptor().getMessageTypes())
            .add(cosmos.base.v1beta1.CoinOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.benchmark.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.benchmark.v1.Benchmark.getDescriptor().getMessageTypes())
            .add(cosmos.benchmark.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.circuit.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.circuit.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.circuit.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.circuit.v1.Types.getDescriptor().getMessageTypes())
            .add(cosmos.consensus.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.consensus.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.consensus.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.counter.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.counter.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.counter.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.crisis.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.crisis.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.crisis.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.ed25519.Keys.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.hd.v1.Hd.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.keyring.v1.RecordOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.multisig.Keys.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.multisig.v1beta1.Multisig.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.secp256k1.Keys.getDescriptor().getMessageTypes())
            .add(cosmos.crypto.secp256r1.Keys.getDescriptor().getMessageTypes())
            .add(cosmos.distribution.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.distribution.v1beta1.Distribution.getDescriptor().getMessageTypes())
            .add(cosmos.distribution.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.distribution.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.distribution.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.epochs.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.epochs.v1beta1.Events.getDescriptor().getMessageTypes())
            .add(cosmos.epochs.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.epochs.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.evidence.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.evidence.v1beta1.Evidence.getDescriptor().getMessageTypes())
            .add(cosmos.evidence.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.evidence.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.evidence.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.feegrant.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.feegrant.v1beta1.Feegrant.getDescriptor().getMessageTypes())
            .add(cosmos.feegrant.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.feegrant.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.feegrant.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.genutil.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.genutil.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.gov.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1.Gov.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1beta1.Gov.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.gov.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.group.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.group.v1.Events.getDescriptor().getMessageTypes())
            .add(cosmos.group.v1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.group.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.group.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.group.v1.Types.getDescriptor().getMessageTypes())
            .add(cosmos.mint.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.mint.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.mint.v1beta1.Mint.getDescriptor().getMessageTypes())
            .add(cosmos.mint.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.mint.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.msg.textual.v1.Textual.getDescriptor().getMessageTypes())
            .add(cosmos.msg.v1.Msg.getDescriptor().getMessageTypes())
            .add(cosmos.nft.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.nft.v1beta1.Event.getDescriptor().getMessageTypes())
            .add(cosmos.nft.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.nft.v1beta1.Nft.getDescriptor().getMessageTypes())
            .add(cosmos.nft.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.nft.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.params.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.params.v1beta1.Params.getDescriptor().getMessageTypes())
            .add(cosmos.params.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.protocolpool.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.protocolpool.v1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.protocolpool.v1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.protocolpool.v1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.protocolpool.v1.Types.getDescriptor().getMessageTypes())
            .add(cosmos.query.v1.Query.getDescriptor().getMessageTypes())
            .add(cosmos.reflection.v1.Reflection.getDescriptor().getMessageTypes())
            .add(cosmos.slashing.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.slashing.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.slashing.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.slashing.v1beta1.Slashing.getDescriptor().getMessageTypes())
            .add(cosmos.slashing.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.staking.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.staking.v1beta1.Authz.getDescriptor().getMessageTypes())
            .add(cosmos.staking.v1beta1.Genesis.getDescriptor().getMessageTypes())
            .add(cosmos.staking.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.staking.v1beta1.Staking.getDescriptor().getMessageTypes())
            .add(cosmos.staking.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.store.internal.kv.v1beta1.Kv.getDescriptor().getMessageTypes())
            .add(cosmos.store.snapshots.v1.SnapshotOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.store.streaming.abci.Grpc.getDescriptor().getMessageTypes())
            .add(cosmos.store.v1beta1.CommitInfoOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.store.v1beta1.Listening.getDescriptor().getMessageTypes())
            .add(cosmos.tx.config.v1.ConfigOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.tx.signing.v1beta1.Signing.getDescriptor().getMessageTypes())
            .add(cosmos.tx.v1beta1.ServiceOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.tx.v1beta1.TxOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.upgrade.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.upgrade.v1beta1.QueryOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.upgrade.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.upgrade.v1beta1.Upgrade.getDescriptor().getMessageTypes())
            .add(cosmos.vesting.module.v1.ModuleOuterClass.getDescriptor().getMessageTypes())
            .add(cosmos.vesting.v1beta1.Tx.getDescriptor().getMessageTypes())
            .add(cosmos.vesting.v1beta1.Vesting.getDescriptor().getMessageTypes())
            .add(cosmos_proto.Cosmos.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.agent.AgentProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.agent.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.agent.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.agent.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.asset.AssetProto.getDescriptor().getMessageTypes())
//            .add(exchange.antx.proto.chain.asset.DepositProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.asset.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.asset.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.asset.TxProto.getDescriptor().getMessageTypes())
//            .add(exchange.antx.proto.chain.asset.WithdrawProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.AdProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.CategoryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.PostProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.ProductProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.demo.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.exchange.ExchangeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.exchange.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.exchange.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.exchange.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.funding.FundingProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.funding.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.funding.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.funding.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.match.MatchProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.match.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.match.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.match.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.offchain.OffchainProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.offchain.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.offchain.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.offchain.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.order.OrderProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.order.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.order.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.order.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.price.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.price.PriceProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.price.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.price.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.subaccount.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.subaccount.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.subaccount.SubaccountProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.subaccount.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.vault.ParamsProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.vault.QueryProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.vault.ShareProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.vault.TxProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.chain.vault.VaultProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.common.CommonProto.getDescriptor().getMessageTypes())
//            .add(exchange.antx.proto.server.asset.AssetEventProto.getDescriptor().getMessageTypes())
//            .add(exchange.antx.proto.server.asset.AssetRpcProto.getDescriptor().getMessageTypes())
//            .add(exchange.antx.proto.server.asset.AssetTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.faucet.FaucetEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.faucet.FaucetRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.faucet.FaucetTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.funding.FundingEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.funding.FundingRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.indexer.IndexerEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.indexer.IndexerRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.indexer.IndexerTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.liquidate.LiquidateRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.liquidate.LiquidateTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.offchain.OffchainRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.points.PointsEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.points.PointsRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.points.PointsTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.price.PriceEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.price.PriceRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.quote.QuoteEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.quote.QuoteRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.quote.QuoteTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.stats.StatsRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.stats.StatsTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.user.UserEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.user.UserRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.user.UserTypeProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.vault.VaultEventProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.vault.VaultRpcProto.getDescriptor().getMessageTypes())
            .add(exchange.antx.proto.server.vault.VaultTypeProto.getDescriptor().getMessageTypes())
            .add(io.grpc.binarylog.v1.BinaryLogProto.getDescriptor().getMessageTypes())
            .add(io.grpc.channelz.v1.ChannelzProto.getDescriptor().getMessageTypes())
            .add(io.grpc.health.v1.HealthProto.getDescriptor().getMessageTypes())
            .add(io.grpc.reflection.v1.ServerReflectionProto.getDescriptor().getMessageTypes())
            // .add(io.grpc.reflection.v1alpha.ServerReflectionProto.getDescriptor().getMessageTypes())
            .add(tendermint.abci.Types.getDescriptor().getMessageTypes())
            .add(tendermint.blocksync.Types.getDescriptor().getMessageTypes())
            .add(tendermint.consensus.Types.getDescriptor().getMessageTypes())
            .add(tendermint.consensus.Wal.getDescriptor().getMessageTypes())
            .add(tendermint.crypto.Keys.getDescriptor().getMessageTypes())
            .add(tendermint.crypto.ProofOuterClass.getDescriptor().getMessageTypes())
            .add(tendermint.libs.bits.Types.getDescriptor().getMessageTypes())
            .add(tendermint.mempool.Types.getDescriptor().getMessageTypes())
            .add(tendermint.p2p.Conn.getDescriptor().getMessageTypes())
            .add(tendermint.p2p.Pex.getDescriptor().getMessageTypes())
            .add(tendermint.p2p.Types.getDescriptor().getMessageTypes())
            .add(tendermint.privval.Types.getDescriptor().getMessageTypes())
            .add(tendermint.rpc.grpc.Types.getDescriptor().getMessageTypes())
            .add(tendermint.state.Types.getDescriptor().getMessageTypes())
            .add(tendermint.statesync.Types.getDescriptor().getMessageTypes())
            .add(tendermint.store.Types.getDescriptor().getMessageTypes())
            .add(tendermint.types.BlockOuterClass.getDescriptor().getMessageTypes())
            .add(tendermint.types.Canonical.getDescriptor().getMessageTypes())
            .add(tendermint.types.Events.getDescriptor().getMessageTypes())
            .add(tendermint.types.EvidenceOuterClass.getDescriptor().getMessageTypes())
            .add(tendermint.types.Params.getDescriptor().getMessageTypes())
            .add(tendermint.types.Types.getDescriptor().getMessageTypes())
            .add(tendermint.types.ValidatorOuterClass.getDescriptor().getMessageTypes())
            .add(tendermint.version.Types.getDescriptor().getMessageTypes())
            .build();

    private static final JsonFormat.Printer JSON_FORMAT_PRINTER = JsonFormat.printer()
            .preservingProtoFieldNames()
            .omittingInsignificantWhitespace()
            .includingDefaultValueFields()
            // .alwaysPrintFieldsWithNoPresence()
            .sortingMapKeys()
            .usingTypeRegistry(TYPE_REGISTRY);

    public static String printJsonQuietly(MessageOrBuilder messageOrBuilder) {
        if (messageOrBuilder == null) {
            return null;
        } else {
            try {
                return JSON_FORMAT_PRINTER.print(messageOrBuilder);
            } catch (InvalidProtocolBufferException e) {
                Throwables.throwIfUnchecked(e);
                throw new RuntimeException(e);
            }
        }
    }

    public static <T extends MessageOrBuilder> String printJsonListQuietly(List<T> messageOrBuilderList) {
        if (messageOrBuilderList == null || messageOrBuilderList.isEmpty()) {
            return null;
        } else {
            try {
                return messageOrBuilderList.stream().map(item -> {
                    try {
                        return JSON_FORMAT_PRINTER.print(item);
                    } catch (InvalidProtocolBufferException e) {
                        throw new RuntimeException(e);
                    }
                }).collect(Collectors.joining(", ", "[", "]"));
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }

    private static final JsonFormat.Printer JSON_FORMAT_PRINTER_PRETTY = JsonFormat.printer()
            .preservingProtoFieldNames()
            .includingDefaultValueFields()
            // .alwaysPrintFieldsWithNoPresence()
            .sortingMapKeys()
            .usingTypeRegistry(TYPE_REGISTRY);

    public static String printJsonQuietlyPretty(MessageOrBuilder messageOrBuilder) {
        if (messageOrBuilder == null) {
            return null;
        } else {
            try {
                return JSON_FORMAT_PRINTER_PRETTY.print(messageOrBuilder);
            } catch (InvalidProtocolBufferException e) {
                Throwables.throwIfUnchecked(e);
                throw new RuntimeException(e);
            }
        }
    }

}
